DROP DATABASE IF EXISTS `tracker_db`;
CREATE DATABASE `tracker_db`;
USE `tracker_db`;
CREATE TABLE `DEPARTMENTS` (
    `ID` INT PRIMARY KEY,
    `NAME` VARCHAR(30) NOT NULL
);
CREATE TABLE `ROLES` (
    `ID` INT PRIMARY KEY,
    `TITLE` VARCHAR(30) NOT NULL,
    `SALARY` DECIMAL(10, 2) NOT NULL,
    `DEPARTMENT_ID` INT
);
CREATE TABLE `EMPLOYEE` (
    `ID` INT PRIMARY KEY,
    `FIRST_NAME` VARCHAR(30) NOT NULL,
    `LAST_NAME` VARCHAR(30) NOT NULL,
    `ROLE_ID` INT,
    `MANAGER_ID` INT
);